### PR TITLE
feat: add SwitchPalettePlugin to ExtensionsCollection

### PR DESCRIPTION
**Pull request by PengjuYan**
Hi Yakov, this is to add my SwitchPalettePlugin to the extension list of EEP, in response to your [suggestions here](https://groups.google.com/g/tiddlywikiclassic/c/6VFoIOUnJ9w/m/A9TzupWVAAAJ).

1. Tell me if it is better to put it in SingleIndex instead.
2. I'll fix my plugin after I got your instruction about my [question here](https://groups.google.com/g/tiddlywikiclassic/c/6VFoIOUnJ9w/m/6Y10ANezAQAJ).

### CODE REVIEW

**Comment by YakovL** [comment]
Hi @PengjuYan, thanks, for now it's fine adding to the ExtensionsCollection (the SingleIndex initiative is more about gathering various "unprepared" plugins in one place, including those available only inside a TW, and it got out of my focus for now)

**Comment by YakovL** [comment]
But please also bump the version of the collection (to 0.1.1) so that others will get a collection update and hence can see there's something new

**Comment by PengjuYan** [comment]
> But please also bump the version of the collection (to 0.1.1) so that others will get a collection update and hence can see there's something new

Hi @YakovL , changed the version to 0.1.1.

PS: a newline character was added automatically by my editor (not sure it was emacs or visual studio code). I personally like the idea of keeping each file end with a newline.

**Comment by YakovL** [comment]
Thanks, Pengju, I've included this PR as an example into the "for authors" section which I'll add to the collection description later (or may be to a separate doc)

**Pull request merged**
